
# tap repositories and their packages

tap homebrew/core
brew aom
brew appstream
brew aria2
brew aribb24
brew at-spi2-core
brew bash
brew bat
brew bison
brew brotli
brew c-ares
brew ca-certificates
brew cabextract
brew cairo
brew carthage
brew certifi
brew cffi
brew cjson
brew clangql
brew cmake
brew cryptography
brew dav1d
brew dbus
brew duti
brew eza
brew faac
brew faad2
brew fdk-aac
brew ffmpeg
brew fish
brew flac
brew flex
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gcc
brew gdk-pixbuf
brew gettext
brew ghostscript
brew giflib
brew gitoxide
brew gitup
brew glib
brew glib-networking
brew gmp
brew gnutls
brew go
brew gobject-introspection
brew graphene
brew graphite2
brew gsettings-desktop-schemas
brew gstreamer
brew gtk+3
brew gtk4
brew harfbuzz
brew hicolor-icon-theme
brew highway
brew icu4c@76
brew imagemagick
brew imath
brew img2pdf
brew isl
brew jasper
brew jbig2dec
brew jbig2enc
brew jpeg-turbo
brew jpeg-xl
brew jq
brew json-glib
brew kondo
brew lame
brew leptonica
brew libadwaita
brew libarchive
brew libass
brew libb2
brew libbluray
brew libcuefile
brew libde265
brew libdeflate
brew libepoxy
brew libevent
brew libgit2
brew libgit2@1.8
brew libheif
brew libidn
brew libidn2
brew libimagequant
brew liblqr
brew libmicrohttpd
brew libmpc
brew libnghttp2
brew libnice
brew libogg
brew libomp
brew libpng
brew libpsl
brew libraqm
brew libraw
brew libreplaygain
brew librist
brew libsamplerate
brew libsass
brew libshout
brew libsndfile
brew libsodium
brew libsoup
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusrsctp
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxfixes
brew libxi
brew libxmlb
brew libxrender
brew libxtst
brew libyaml
brew little-cms2
brew lld
brew llvm
brew lua
brew lz4
brew lzo
brew m4
brew mbedtls
brew micro
brew mingw-w64
brew molten-vk
brew mpdecimal
brew mpfr
brew mpg123
brew musepack
brew ncurses
brew nettle
brew node
brew ocrmypdf
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@3
brew opus
brew orc
brew p11-kit
brew p7zip
brew pandoc
brew pango
brew pcre
brew pcre2
brew pdm
brew pillow
brew pixman
brew pkgconf
brew pngquant
brew py3cairo
brew pybind11
brew pycparser
brew pygobject3
brew python-packaging
brew python@3.12
brew python@3.13
brew qpdf
brew rav1e
brew readline
brew rip2
brew ripgrep
brew rtmpdump
brew rubberband
brew rust
brew sdl2
brew shared-mime-info
brew snappy
brew speex
brew sqlite
brew srt
brew srtp
brew svt-av1
brew taglib
brew tealdeer
brew tesseract
brew tesseract-lang
brew theora
brew topgrade
brew unbound
brew unpaper
brew unzip
brew webp
brew winetricks
brew x264
brew x265
brew xorgproto
brew xvid
brew xz
brew yazi
brew z3
brew zenity
brew zeromq
brew zimg
brew zoxide
brew zsh
brew zstd

tap homebrew/cask
cask balenaetcher
cask beeper
cask carbon-copy-cloner
cask cold-turkey-blocker
cask coteditor
cask cyberduck
cask exifcleaner
cask fastdmg
cask font-0xproto-nerd-font
cask font-3270-nerd-font
cask font-agave-nerd-font
cask font-anonymice-nerd-font
cask font-arimo-nerd-font
cask font-aurulent-sans-mono-nerd-font
cask font-bigblue-terminal-nerd-font
cask font-bitstream-vera-sans-mono-nerd-font
cask font-blex-mono-nerd-font
cask font-caskaydia-cove-nerd-font
cask font-caskaydia-mono-nerd-font
cask font-code-new-roman-nerd-font
cask font-comic-shanns-mono-nerd-font
cask font-commit-mono-nerd-font
cask font-cousine-nerd-font
cask font-d2coding-nerd-font
cask font-daddy-time-mono-nerd-font
cask font-dejavu-sans-mono-nerd-font
cask font-departure-mono-nerd-font
cask font-droid-sans-mono-nerd-font
cask font-envy-code-r-nerd-font
cask font-fantasque-sans-mono-nerd-font
cask font-fira-code-nerd-font
cask font-fira-mono-nerd-font
cask font-geist-mono-nerd-font
cask font-go-mono-nerd-font
cask font-gohufont-nerd-font
cask font-hack-nerd-font
cask font-hasklug-nerd-font
cask font-heavy-data-nerd-font
cask font-hurmit-nerd-font
cask font-im-writing-nerd-font
cask font-inconsolata-go-nerd-font
cask font-inconsolata-lgc-nerd-font
cask font-inconsolata-nerd-font
cask font-intone-mono-nerd-font
cask font-iosevka-nerd-font
cask font-iosevka-term-nerd-font
cask font-iosevka-term-slab-nerd-font
cask font-jetbrains-mono-nerd-font
cask font-lekton-nerd-font
cask font-liberation-nerd-font
cask font-lilex-nerd-font
cask font-m+-nerd-font
cask font-martian-mono-nerd-font
cask font-meslo-lg-nerd-font
cask font-monocraft-nerd-font
cask font-monofur-nerd-font
cask font-monoid-nerd-font
cask font-mononoki-nerd-font
cask font-noto-nerd-font
cask font-open-dyslexic-nerd-font
cask font-overpass-nerd-font
cask font-profont-nerd-font
cask font-proggy-clean-tt-nerd-font
cask font-recursive-mono-nerd-font
cask font-roboto-mono-nerd-font
cask font-sauce-code-pro-nerd-font
cask font-sf-pro
cask font-shure-tech-mono-nerd-font
cask font-space-mono-nerd-font
cask font-symbols-only-nerd-font
cask font-terminess-ttf-nerd-font
cask font-tinos-nerd-font
cask font-ubuntu-mono-nerd-font
cask font-ubuntu-nerd-font
cask font-ubuntu-sans-nerd-font
cask font-victor-mono-nerd-font
cask font-zed-mono-nerd-font
cask gcc-aarch64-embedded
cask ghostty@tip
cask gstreamer-runtime
cask imageoptim
cask karabiner-elements
cask keka
cask lingon-x
cask mac-mouse-fix
cask macupdater
cask monero-wallet
cask mountain-duck
cask nrlquaker-winbox
cask obsidian
cask orbstack
cask orion
cask pictogram
cask raycast
cask swiftdefaultappsprefpane
cask tor-browser@alpha
cask utm@beta
cask whisky
cask wine@staging
cask xquartz

tap homebrew/services

tap felixkratz/formulae
brew borders
brew sketchybar

tap gcenx/wine
cask kegworks

tap idleberg/macports

tap joseluisq/paket

tap mac-cleanup/mac-cleanup-py
brew mac-cleanup-py

tap macos-fuse-t/cask
cask fuse-t
cask fuse-t-sshfs

tap nikitabobko/tap
cask aerospace

tap rcmdnk/file
brew brew-file

tap wyne/tap
