# AEROSPACE CONFIG
start-at-login = true

after-login-command = []

after-startup-command = [
     'exec-and-forget borders active_color=0xffffffff inactive_color=0xffffffff style=square width=1.0'
#     'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar'
]

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]


on-focus-changed = [
  'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

enable-normalization-flatten-containers = true

enable-normalization-opposite-orientation-for-nested-containers = true

automatically-unhide-macos-hidden-apps = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'horizontal'

key-mapping.preset = 'qwerty'

[gaps]
#outer.bottom numbers have to match presentation.sh variables. built-in retina display is excluded from presentation mode, so this only works on external monitors.
outer.bottom =        [{monitor.'^built-in retina display$' = 0 }, 0]
outer.top =        [{monitor.'^built-in retina display$' = 0 }, 0]
outer.left =       0
outer.right =      0
inner.horizontal = 15
inner.vertical =   15

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
cmd-alt-ctrl-shift-enter = 'layout floating tiling'

shift-cmd-w = [
  'close --quit-if-last-window'
]

cmd-q = [
  'close --quit-if-last-window'
]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

#cmd-enter = 'exec-and-forget open -n /Volumes/Macintosh\ HD/Applications/Alacritty.app'
#cmd-m = 'exec-and-forget open -n /Volumes/Macintosh\ HD/Applications/Marta.app'

cmd-shift-f = 'fullscreen'

#cmd-shift-h = 'move left'
#cmd-shift-j = 'move down'
#cmd-shift-k = 'move up'
#cmd-shift-l = 'move right'


#cmd-1 = 'summon-workspace 1'  # Notes
f1 = 'workspace --auto-back-and-forth 1'  # Notes
f2 = 'workspace --auto-back-and-forth 2'  # Terminal
f3 = 'workspace --auto-back-and-forth 3'  # Browser
f4 = 'workspace --auto-back-and-forth 4'  # AltBrowser
f5 = 'workspace --auto-back-and-forth 5'  # Remote
f6 = 'workspace --auto-back-and-forth 6'  # Database
f7 = 'workspace --auto-back-and-forth 7'  # Chat
f8 = 'workspace --auto-back-and-forth 8'  # Mail
f9 = 'workspace --auto-back-and-forth 9'  # Music
f10 = 'workspace --auto-back-and-forth 10' # Secrets
f11 = 'workspace --auto-back-and-forth 11'  # Meeting
f12 = 'workspace --auto-back-and-forth 12'  # 
f13 = 'workspace --auto-back-and-forth 13'  # 
f14 = 'workspace --auto-back-and-forth 14'  # 
f15 = 'workspace --auto-back-and-forth 15'  # 
f16 = 'workspace --auto-back-and-forth 16'  # 
f17 = 'workspace --auto-back-and-forth 17'  # 
f18 = 'workspace --auto-back-and-forth 18'  # 


cmd-alt-ctrl-shift-f1 = 'move-node-to-workspace 1'
cmd-alt-ctrl-shift-f2 = 'move-node-to-workspace 2'
cmd-alt-ctrl-shift-f3 = 'move-node-to-workspace 3'
cmd-alt-ctrl-shift-f4 = 'move-node-to-workspace 4'
cmd-alt-ctrl-shift-f5 = 'move-node-to-workspace 5'
cmd-alt-ctrl-shift-f6 = 'move-node-to-workspace 6'
cmd-alt-ctrl-shift-f7 = 'move-node-to-workspace 7'
cmd-alt-ctrl-shift-f8 = 'move-node-to-workspace 8'
cmd-alt-ctrl-shift-f9 = 'move-node-to-workspace 9'
cmd-alt-ctrl-shift-f10 = 'move-node-to-workspace 10'
cmd-alt-ctrl-shift-f11 = 'move-node-to-workspace 11'
cmd-alt-ctrl-shift-f12 = 'move-node-to-workspace 12'


alt-tab = 'workspace-back-and-forth'

cmd-alt-h = []



[[on-window-detected]]
if.app-id = 'com.kagi.kagimacOS'
run = ['layout tiling', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['layout tiling', 'move-node-to-workspace 5']


[[on-window-detected]]
if.app-id = 'com.binarynights.ForkLift'              
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.coteditor.CotEditor'              
run = ['move-node-to-workspace 4']
